name: on-push-main
on:
  push:
    branches:
    - main
    paths:
      - '.github/workflows/on-push-main.yaml'
      - '.github/workflows/on-version-tagged.yaml'
      - '.gitops/**'
      - 'apis/**'
      - 'examples/**'
      - 'functions/**'
      - 'tests/**'
      - 'upbound.yaml'

permissions:
  id-token: write
  packages: write
  contents: write
  issues: write
  pull-requests: write

jobs:

  validate:
    uses: unbounded-tech/workflows-crossplane/.github/workflows/validate.yaml@v2.13.0
    with:
      examples: |
        [
          { "example": "examples/ipv6ulanetworkallocations/minimal.yaml" },
          { "example": "examples/ipv6ulanetworkallocations/standard.yaml" },
          { "example": "examples/ipv6ulanetworkallocations/custom-sizes.yaml" },
          { "example": "examples/ipv6ulanetworkallocations/standard.yaml", "observed_resources": "examples/test/mocks/observed-resources/standard/steps/1/" },
          { "example": "examples/ipv6ulanetworkallocations/standard.yaml", "observed_resources": "examples/test/mocks/observed-resources/standard/steps/2/" },
          { "example": "examples/ipv6ulanetworkallocations/standard.yaml", "observed_resources": "examples/test/mocks/observed-resources/standard/steps/3/" }
        ]
      api_path: apis/ipv6ulanetworkallocations
      error_on_missing_schemas: true

  test:
    uses: unbounded-tech/workflows-crossplane/.github/workflows/test.yaml@v2.13.0

  e2e:
    uses: unbounded-tech/workflows-crossplane/.github/workflows/e2e.yaml@v2.13.0
    with:
      aws: true
      aws-use-oidc: true
      aws-account-id: "034489662075"
      aws-region: us-east-2

  version-and-tag:
    name: Version and Tag
    needs:
      - validate
      - test
      - e2e
    uses: unbounded-tech/workflow-vnext-tag/.github/workflows/workflow.yaml@v1.20.2
    secrets:
      DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
    with:
      useDeployKey: true
      yqPatches: |
        patches:
          - filePath: .gitops/deploy/values.yaml
            selector: .version
            valuePrefix: "v"
          - filePath: .gitops/deploy/Chart.yaml
            selector: .version
            valuePrefix: ""
